### ISSUE TITLE
Use node-pre-gyp

### ISSUE THREAD

**Issue by Pomax** [karma-runner/karma-cli#12]
Any Nodejs/npm module that relies on node-gyp basically means Windows users can't use your project without compiling, which is an incredibly much harder dev track than on OSX and Unix/Linux. However, that problem can be entirely negated by using [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp), so I cannot stress enough how important it is to work that into karma=cli, so that webpack-dev-server (which relies on karma-cli) can actually run on Windows, instead of somewhat (hopefully unintentionally, of course!) giving them the finger

A fantastic example is sqlite3 - install that on any OS and instead of compiling it just checks if there is a precompiled version on S3. If so, it downloads that, and done. Especially for windows users, that makes the difference between "I can't use this module" and "everything just works" =)

**Comment by Dignifiedquire** [comment]
Thanks for the suggestion, though I think this is the wrong repo to address this. `karma-cli` itself has no dependencies that require compiling, rather `karma` itself has some.

**Comment by Pomax** [comment]
cheers, I'll file that on them then!
