### ISSUE TITLE
package is overly restrictive about installation environment

### ISSUE THREAD

**Issue by sam-github** [karma-runner/karma-cli#13]
https://github.com/karma-runner/karma-cli/blob/master/package.json#L45-L51

karma is perfectly suited to be used as a dev-dependency for unit testing, but preferring global causes npm installs to warn.

karma works fine on stable node versions, not just the legacy 0.8/0.10, despite the npm warning about engine unsupported, I suggest removing the engine spec, or at least allowing `>= 0.8`.

**Comment by matanster** [comment]
What about node version 4? doesn't the test suite cater for a quick verification of that version as well?

**Comment by Dignifiedquire** [comment]
Yes this should be updated to the same versions as `karma` itself supports
