### ISSUE TITLE
Illegal instruction on windows

### ISSUE THREAD

**Issue by warapitiya** [karma-runner/karma-cli#20]
I'm trying to run the hello world karma project but it gives me a error saying 

```
/c/Users/myname/AppData/Roaming/npm/karma: line 14:  2808 Illegal instruction     node "$basedir/node_modules/karma-cli/bin/karma" "$@"
```

Tried reinstalling every module one bye one. same thing occurs. 

I installed

```
npm i karma-cli -g
npm i karma --save-dev
```

Using a Windows 7 (64bit)
Nodejs V4.4.5 (x64)

**Comment by rogeriopvl** [comment]
@warapitiya is this still an issue? If not, I'm closing it in a couple of days.
