### ISSUE TITLE
Update version so npm recognizes new package.json

### ISSUE THREAD

**Issue by VernacularHam** [karma-runner/karma-cli#45]
The current 1.0.1 of karma-cli on npmjs.org doesn't contain your updated package.json that supports v8 of Node.js

**Comment by VernacularHam** [comment]
So anyone using the new LTS of Node.js gets an unsupported error when trying to install Karma-cli from npm.

**Comment by XavierDupessey** [comment]
+1

NPM still see _"engines": { "node": "0.10 || 0.12 || 4 || 5 || 6" }_ for karma-cli v1.0.1

**Comment by rogeriopvl** [comment]
@dignifiedquire can you do a release to include the latest changes? Thanks!

**Comment by rogeriopvl** [comment]
Closing this since a 2.0.0 release has been done in the meantime.
