### ISSUE TITLE
Argument parser does not warn of invalid arguments

### ISSUE THREAD

**Issue by lietu** [karma-runner/karma-cli#6]
I was wondering for some time why my karma wasn't running my tests in PhantomJS like I was asking it.

I was trying to run:

```
karma start --browser PhantomJS
```

I reinstalled phantomjs, karma-cli, updated the karma-phantomjs-launcher, etc., before I found the argument for enabling debug messages.

Then I realized it wasn't even acknowledging that I asked it to launch the browser, thought it was a configuration issue, and then I noticed the missing "s" from `--browsers`.

Just a simple error/warning message would've saved me a fair bit of time, such as:

```
Invalid argument --browser
```

Running Karma v0.12.19

**Comment by rogeriopvl** [comment]
Closing this. If still relevant, this should be reported in [karma-runner/karma](https://github.com/karma-runner/karma), since the code that parses cli args is in [lib/cli.js](https://github.com/karma-runner/karma/blob/master/lib/cli.js).
